### ISSUE TITLE
Different inertial values: 

### ISSUE THREAD

**Issue by wyqsnddd** [jrl-umi3218/mc_panda#15]
Hi Pierre @gergondet ! 

I just noticed the recent `inertial parameter`'s update on Feb. 11th: 

```sh
commit d965cc62994761c4a1a60062dc2940553650f14c (HEAD -> master, origin/master, origin/HEAD)
Author: Pierre Gergondet <pierre.gergondet@gmail.com>
Date:   Fri Feb 11 17:47:29 2022 +0800

    Use the inertial parameters released by Franka Emika

```

The update keeps the kinematics but introduces a considerable change of the link mass:

### New version: 
```sh
The robot links are:
link:panda_link1 mass: 4.97068
The Parent joint tf: is: 
 0.197735 -0.980255         0         0
 0.980255  0.197735         0         0
        0         0         1     0.333
        0         0         0         1
-------
link:panda_link2 mass: 0.646926
The Parent joint tf: is: 
  0.0719242    0.184191   -0.980255           0
   0.356558    0.913108    0.197735           0
   0.931501    -0.36374 4.89664e-12       0.333
          0           0           0           1
-------
```

### Old version
```sh
The robot links are:
link:panda_link1 mass: 2.74
The Parent joint tf: is: 
 0.197735 -0.980255         0         0
 0.980255  0.197735         0         0
        0         0         1     0.333
        0         0         0         1
-------
link:panda_link2 mass: 2.74
The Parent joint tf: is: 
  0.0719242    0.184191   -0.980255           0
   0.356558    0.913108    0.197735           0
   0.931501    -0.36374 4.89664e-12       0.333
          0           0           0           1
-------

```

As a result, my computations, such as the `inverse inertia matrix`, changed significantly. I am wondering, is this update reliable enough, or necessary? 

For example, `panda_link1` and `panda_link2` are almost identical. Why are their mass nearly 10 times different from each other in the new update?

**Comment by gergondet** [comment]
Hi Yuquan,

> I am wondering, is this update reliable enough, or necessary?

The new data is based on the data provided by Franka Emika in their repository whereas the previous data was based on estimation based on the shape of the links and total mass of the robot ([ref](https://erdalpekel.de/?p=55)). So it's definitely more accurate.

What I heard from folks using mc_rtc to torque control the Panda is that they were already using different inertial parameters than the one in this repo (based on the identification work by [Gaz et al.](https://hal.inria.fr/hal-02265293/document))

> Why are their mass nearly 10 times different from each other in the new update?

Probably one of the two links has more hardware inside than the other one.
