### ISSUE TITLE
pump surface problem in rsdf file

### ISSUE THREAD

**Issue by ndehio** [jrl-umi3218/mc_panda#4]
In the file [panda_pump.rsdf](https://github.com/jrl-umi3218/mc_panda/blob/master/data/rsdf/panda_pump/panda_pump.rsdf#L4) the line ```  <planar_surface name="Pump" link="panda_pump"> ``` causes an error when executing:
``` ctl.robot( robotName ).surfaceForceSensor( "Pump" ) ```

Changing this line to ```   <planar_surface name="Pump" link="panda_link7"> ``` solves the problem.

**Comment by gergondet** [comment]
@ndehio that's because the force sensor is attached to `panda_link7` and not the pump. You can retrieve the force sensor via `robot().indirectSurfaceForceSensor("Pump")`

**Comment by ndehio** [comment]
you are perfectly right, thanks!
