### ISSUE TITLE
Cnoid scene with a wall

### ISSUE THREAD

**Issue by wyqsnddd** [jrl-umi3218/mc_panda#5]
Hi Pierre,

To validate the impact models, I need a cnoid scene with a panda and a wall, e.g. with my own [implementation](https://github.com/wyqsnddd/mc_panda/blob/master/data/cnoid/common/sim_mc_wall.cnoid)

However, it is not successful, right after `--start-simulation`, the robot would generate some random behavior and lost. Could you please create such a scene? This task has a high priority at the moment. 

![Screenshot from 2021-02-11 12-25-45](https://user-images.githubusercontent.com/6009684/107630813-627fbc80-6c64-11eb-8867-a314343cf136.png)
![Screenshot from 2021-02-11 12-24-51](https://user-images.githubusercontent.com/6009684/107630816-63185300-6c64-11eb-97e9-83d97b850dda.png)

**Comment by gergondet** [comment]
Closing this.

This was due to a configuration issue with omniORB, `giopMaxMsgSize` should be multiplied by 100 from the default value in Ubuntu's `/etc/omniORB.cfg`
